### ISSUE TITLE
johnny-cache doesn't update cache after update data from manage.py command.

### ISSUE THREAD

**Issue by inlanger** [jmoiron/johnny-cache#17]
I use some manage.py command to parse and upload some data to my database. johnny-cache cached my data once and after updates my data cache doesn't update. In database I have actual data, but my site show old data from cache.

I have to restart my memcached server to solve that problem after each data update. Anyone has similar problem?

**Comment by whatisjasongoldstein** [comment]
Your problem is that JC is activated in middleware, and management commands don't pass through middleware. This is [pretty well documented](http://pythonhosted.org/johnny-cache/queryset_cache.html#using-with-scripts-management-commands-asynchronous-workers-and-the-shell) and can be fixed either by activating JC in your script, or by [manually clearing](http://pythonhosted.org/johnny-cache/queryset_cache.html#manual-invalidation) the models you affect.

**Comment by jself** [comment]
We've looked into solutions for this, and Django doesn't make it particularly easy due to the order of instantiation of the database/settings/etc. For now we'll leave it as activating JC in the script itself.

**Comment by jmoiron** [comment]
After some discussion in an email thread, I think it would work to have the `__init__.py` in your project directory (the place your `DJANGO_SETTINGS_MODULE` is) run code like this:

``` python
from johnny.cache import enable
enable()
```

This will make its way to the docs when 1.5 is released in the coming weeks.
