### ISSUE TITLE
Strange issues with caches not being invalidated and getting "stuck"

### ISSUE THREAD

**Issue by tesh11** [jmoiron/johnny-cache#8]
We're using johnny cache in a multi-web server environment and we're running into some strange issues in which query caches aren't being invalidated. Unfortunately, we haven't been able to figure out how to reproduce it though it does happen consistently.

We're set up at EC2 and we have 2 web servers set up using nginx + uwsgi. We're only using one db (pooled using pgbouncer on each webserver) and have johnny cache configured to use the memcached backend with ElastiCache.

Most of our code uses Django's default autocommit mode but we do have some methods where we use the @transaction.commit_on_success decorator.

We also have some cron jobs (set up using django-cronjobs) which we run and which need to invalidate caches. In the methods for those cron jobs, we call johhn.cache.enable() to set up johnny cache before we do any other work.

The scenario below works sometimes but then stops working after some time. Once it stops working, we can manually invalidate the object's cache and it starts working again or we can cycle uwsgi on the webservers which also gets things working again.
1. Create a new MyObject (via a form that is saved)
2. In the cronjob, get a list of all MyObjects

Step 2 is what stops working in the sense that new MyObjects don't show up in the list.

We've spent hours trying to track this down so any help you can provide would be great!

**Comment by jmoiron** [comment]
The setup seems a bit complex for me to replicate, so perhaps if I suggest some things you can do to debug this and perhaps some more information which could help me figure out what might be going on.

First, some standard sanity checks:
1. the settings on your cron boxes/cron jobs should be the same as the app servers
2. if you're using multiple elasticache nodes, make sure you're using the same memcached library or the same key ballancing algorithm across app & cron
3. make sure that the security groups are set up so that the cron & app servers can reach 11211 on your elasticache group :)

Now for your problem.

Johnny invalidates by writing a new uuid to an algorithmically generated memcached key for a particular table or set of tables.  This is safe even after eviction because if it's not there, it is impossible to then build the keys to find cached data, so the worst thing that can happen is that you have cache misses.

It sounds like your appservers are not invalidating the cache.  It's unlikely that separate cron tasks could somehow get the same stale key, and there's no way to fetch cached data without first fetching the keys described above.  

Invalidation failure can happen for a number of reasons;  maybe the middleware isn't active, or some other codepath somewhere is deactivating it.  Maybe they have lost their connection to the cache, maybe cache cluster ballancing is having them write the key to the wrong node somehow (or a different node than is expected by other servers using a different alg), maybe the table is in the johnny blacklist.  Maybe there is a bug in johnny that is not invalidating on these writes (I always have to admit this possibility, but this aspect is pretty thoroughly tested so a simple CRUD update is almost certainly hitting the right codepath if the config is right).

Since restarting the appservers fixes it, I'd probably look into connection issues between the appservers and the cache cluster.  You could try to add a johnny.cache.invalidate(MyObject) after you save the form in your Django view and see if it still happens.  You could try a simple cache sanity check that logs when a set/get fail.

**Comment by tesh11** [comment]
Thanks for the quick response! Regarding the sanity checks:
1. It's running on one of the app servers using the same codebase and settings so we're all good there.
2. We're only using a single node.
3. The security groups are set up correctly.

Your suggestion that the server could be losing its connection to memcached seems to be on the mark. Running netstat showed that one server had connections to the ElastiCache server while the other server didn't. Cycling uwsgi on the latter caused the connections to be restored.

I'm guessing this is the problem though I'm not sure why the dead connections wouldn't automatically be reconnected. Have you ever experienced this before?

Thanks again!

**Comment by jmoiron** [comment]
It's likely something to do with the underlying memcached library, though I'd find it very worrying that this leads to "cache.set()" failing silently.  If you ever figure this out I'd love to know what it is, it could be pretty important!

I suppose not many things rely on a call to set actually working (since cache misses are generally just a performance impact and not one on correctness), but I wanted to keep johnny free of db models and it'd make little sense to read from the database to see if we have to read from the database (or write twice every time we want to write!).

I'm going to close this out as a memcached library problem but if you discover that it's to do with the code in the johnny backend please re-open.

**Comment by tesh11** [comment]
python-memcached does fail silently on connection errors via set(). It retries the connection but for some reason, that's not working. The reason this causes issues for us is because we now get stale data from the cache as the generation key is never updated.

I'll let you know if I find out anything else. Thanks!

**Comment by emigue** [comment]
Hi tesh11, I imagine that you resolved that problem. We have the same problem and we have found the solution. Johnny-cache write one entry in memcached for every table with some query cached. If one table is invalidated, the entry related to this table changes its value. This entry is used for invalidate the queries about this table. If you use Elasticache with more than one node and use only one end-point from johnny cache, the cluster write the same entry of table in different nodes with distinct values. When johnny cache read from the Elasticache cluster, the cluster returns one of the values that find in the nodes. This will cause that the application will show new data and old data randomly depends of the value returned by the end-point of the Elasticache. The solution to this problem is configure the johnny-cache with every node in the location setting or use only one node.
